# Adult Census Income - Preprocessing

## Phase A - Preprocessing

L'obiettivo di questo notebook è preparare il dataset Adult Census Income per l'addestramento dei modelli di Machine Learning.

Le principali operazioni svolte sono:

1. Caricamento del dataset
2. Pulizia dei dati e gestione dei valori mancanti
3. Codifica delle variabili categoriali tramite One-Hot Encoding
4. Suddivisione in Training Set e Test Set

## 1. Caricamento del dataset Adult Census Income

In questa fase vengono importate le librerie necessarie e viene caricato il dataset Adult Census Income. Successivamente si esegue una prima esplorazione del dataset per comprenderne la struttura, le variabili disponibili e la qualità dei dati.

In [112]:
import pandas as pd
import numpy as np

In [113]:
from sklearn.model_selection import train_test_split

In [114]:
DATA_PATH = "../data/raw/adult.csv"
df = pd.read_csv(DATA_PATH)

In [115]:
df.head() #Verifica del carico

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

In [116]:
#Quante osservazioni contiene il dataset?
print(f"Nombre de lignes : {df.shape[0]}")
print(f"Nombre de colonnes : {df.shape[1]}")

Nombre de lignes : 32561
Nombre de colonnes : 15

In [117]:
df.columns  #Si verifica che tutte le variabili previste siano presenti

Index(['age', 'workclass', 'fnlwgt', 'education', 'education.num',
       'marital.status', 'occupation', 'relationship', 'race', 'sex',
       'capital.gain', 'capital.loss', 'hours.per.week', 'native.country',
       'income'],
      dtype='object')

In [118]:
df.info() #Informazioni generali : il tipo di ciascuna variabile; il numero di valori diversi da zero; la memoria utilizzata.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education.num   32561 non-null  int64
 5   marital.status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital.gain    32561 non-null  int64
 11  capital.loss    32561 non-null  int64
 12  hours.per.week  32561 non-null  int64
 13  native.country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [119]:
df.describe()

,age,fnlwgt,education.num,capital.gain,capital.loss,hours.per.week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [120]:
df.describe(include="object")

,workclass,education,marital.status,occupation,relationship,race,sex,native.country,income
count,32561,32561,32561,32561,32561,32561,32561,32561,32561
unique,9,16,7,15,6,5,2,42,2
top,Private,HS-grad,Married-civ-spouse,Prof-specialty,Husband,White,Male,United-States,<=50K
freq,22696,10501,14976,4140,13193,27816,21790,29170,24720

etape 2 test pour voir le nombre de lignes concernées

In [121]:
# Create a copy of the original dataset
#df_clean = df.copy()
# Replace "?" with NaN
#df_clean.replace("?", np.nan, inplace=True)

In [122]:
# Replace "?" with NaN
#df_clean.replace("?", np.nan, inplace=True)

In [123]:
# Number of rows containing at least one missing value
#rows_with_missing = df_clean.isnull().any(axis=1).sum()

#print(f"Rows with at least one missing value: {rows_with_missing}")

In [124]:
# Total number of rows
#total_rows = len(df_clean)

# Percentage of incomplete rows
#percentage = (rows_with_missing / total_rows) * 100
'''
print(f"Total rows: {total_rows}")
print(f"Incomplete rows: {rows_with_missing}")
print(f"Percentage: {percentage:.2f}%")
'''

'\nprint(f"Total rows: {total_rows}")\nprint(f"Incomplete rows: {rows_with_missing}")\nprint(f"Percentage: {percentage:.2f}%")\n'

In [125]:
#missing_values = df_clean.isnull().sum()
#print(missing_values[missing_values > 0])

## 2. Pulizia dei dati e gestione dei valori mancanti

Prima di addestrare un modello di Machine Learning è necessario verificare la presenza di valori mancanti nel dataset.

Nel dataset Adult Census Income, i valori mancanti sono presenti esclusivamente in alcune variabili categoriche (`workclass`, `occupation` e `native.country`) e sono rappresentati dal simbolo `?`.

Poiché tali valori riguardano esclusivamente attributi categorici e rappresentano una percentuale limitata del dataset, si è scelto di sostituirli con una nuova categoria denominata **"Unknown"** invece di eliminare le osservazioni. Questa scelta consente di preservare tutte le istanze del dataset evitando di introdurre ipotesi arbitrarie tramite imputazione o di perdere informazioni potenzialmente utili per la successiva analisi del bias.

In [126]:
# Create a copy of the original dataset
df_clean = df.copy()

In [127]:
# Remove leading and trailing spaces from categorical columns
for column in df_clean.select_dtypes(include="object").columns:
    df_clean[column] = df_clean[column].str.strip()

In [128]:
# Replace missing values represented by "?" with the category "Unknown"
df_clean.replace("?", "Unknown", inplace=True)

In [ ]:
# Check the number of "Unknown" values in each column

unknown_values = (df_clean == "Unknown").sum()

print("Number of 'Unknown' values per column:\n")
print(unknown_values[unknown_values > 0])

Number of 'Unknown' values per column:

workclass         1836
occupation        1843
native.country     583
dtype: int64

In [130]:
# Check that there are no missing values remaining

print("Missing values remaining:\n")
print(df_clean.isnull().sum())

Missing values remaining:

age               0
workclass         0
fnlwgt            0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
income            0
dtype: int64

## 3. Codifica delle variabili categoriali tramite One-Hot Encoding

I modelli di Machine Learning utilizzati in questo progetto richiedono che tutte le variabili siano rappresentate in forma numerica.

Poiché il dataset contiene diverse variabili categoriche, esse vengono trasformate mediante la tecnica del **One-Hot Encoding**, che crea una variabile binaria per ogni categoria presente nel dataset.

Questa rappresentazione evita di introdurre un ordine artificiale tra categorie nominali e permette ai modelli di interpretare correttamente le informazioni.

## 3. Codifica delle variabili categoriali tramite One-Hot Encoding

I modelli di Machine Learning richiedono che tutte le variabili di input siano rappresentate in forma numerica.

Poiché il dataset contiene diverse variabili categoriche, esse vengono trasformate mediante la tecnica del **One-Hot Encoding**, che crea una variabile binaria per ogni categoria.

La variabile target (`income`) non viene codificata con il One-Hot Encoding, poiché rappresenta la classe da predire. Essendo una classificazione binaria, verrà successivamente convertita nei valori 0 e 1.

In [131]:
# Display categorical columns

categorical_columns = df_clean.select_dtypes(include="object").columns.tolist()

print("Categorical variables:")
print(categorical_columns)

Categorical variables:
['workclass', 'education', 'marital.status', 'occupation', 'relationship', 'race', 'sex', 'native.country', 'income']

In [132]:
# Remove the target variable from the list
categorical_features = categorical_columns.copy()
categorical_features.remove("income")

print(categorical_features)

['workclass', 'education', 'marital.status', 'occupation', 'relationship', 'race', 'sex', 'native.country']

In [133]:
# Apply One-Hot Encoding to categorical features

df_encoded = pd.get_dummies(
    df_clean,
    columns=categorical_features,
    dtype=int
)

In [134]:
print("Dataset shape before encoding:")
print(df_clean.shape)

print("\nDataset shape after encoding:")
print(df_encoded.shape)

Dataset shape before encoding:
(32561, 15)

Dataset shape after encoding:
(32561, 109)

In [135]:
df_encoded.head()

,age,fnlwgt,education.num,capital.gain,capital.loss,hours.per.week,income,workclass_Federal-gov,workclass_Local-gov,workclass_Never-worked,...,native.country_Puerto-Rico,native.country_Scotland,native.country_South,native.country_Taiwan,native.country_Thailand,native.country_Trinadad&Tobago,native.country_United-States,native.country_Unknown,native.country_Vietnam,native.country_Yugoslavia
0,90,77053,9,0,4356,40,<=50K,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,82,132870,9,0,4356,18,<=50K,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,66,186061,10,0,4356,40,<=50K,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,54,140359,4,0,3900,40,<=50K,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,41,264663,10,0,3900,40,<=50K,0,0,0,...,0,0,0,0,0,0,1,0,0,0

## 4. Suddivisione in Training Set e Test Set

L'ultima fase del preprocessing consiste nel preparare il dataset per l'addestramento dei modelli di Machine Learning.

La variabile target (`income`) viene convertita in valori numerici (0 e 1), mentre tutte le altre colonne rappresentano le feature di input.

Successivamente il dataset viene suddiviso in un **Training Set** e un **Test Set**. Il Training Set viene utilizzato per addestrare i modelli, mentre il Test Set viene utilizzato esclusivamente per valutarne le prestazioni su dati mai osservati durante l'addestramento.

In [136]:
# Convert the target variable into binary values

df_encoded["income"] = df_encoded["income"].map({
    "<=50K": 0,
    ">50K": 1
})

In [137]:
# Features
X = df_encoded.drop(columns="income")

# Target
y = df_encoded["income"]

In [138]:
print("Features shape:", X.shape)
print("Target shape:", y.shape)

Features shape: (32561, 108)
Target shape: (32561,)

In [139]:
# Split the dataset into training and testing sets

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [140]:
print(f"Training samples: {X_train.shape[0]}")
print(f"Testing samples: {X_test.shape[0]}")

print(f"Training features: {X_train.shape[1]}")
print(f"Testing features: {X_test.shape[1]}")

Training samples: 26048
Testing samples: 6513
Training features: 108
Testing features: 108

### Salvataggio del Training Set e del Test Set

Per rendere il progetto più modulare e riutilizzabile, il dataset viene suddiviso in un Training Set e in un Test Set. Entrambi vengono salvati nella cartella `data/processed/`.

Nelle fasi successive, ciascun dataset verrà caricato separatamente e solo allora verranno create le variabili **X** (feature) e **y** (target) necessarie per l'addestramento e la valutazione dei modelli.

In [141]:
# Reconstruct the training dataset
train_df = X_train.copy()
train_df["income"] = y_train.values

# Reconstruct the testing dataset
test_df = X_test.copy()
test_df["income"] = y_test.values

In [142]:
# Save the datasets
train_df.to_csv("../data/processed/train.csv", index=False)
test_df.to_csv("../data/processed/test.csv", index=False)

print("Training and testing datasets successfully saved.")

Training and testing datasets successfully saved.